import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { UserProvider } from "@/context/user/UserContext";
import { ThemeProvider } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/theme/theme";
import { AdminProvider } from "@/context/admin/AdminContext";
import { ProjectProvider } from "@/context/projects/ProjectContext";
import { BudgetProvider } from "@/context/budget/BudgetContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "PulseERP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <AdminProvider>
            <BudgetProvider>
              <ProjectProvider>
                <AppRouterCacheProvider>
                  <ThemeProvider theme={theme}>
                    <CssBaseline />
                    {children}
                  </ThemeProvider>
                </AppRouterCacheProvider>
              </ProjectProvider>
            </BudgetProvider>
          </AdminProvider>
        </UserProvider>
      </body>
    </html>
  );
}
